In [1]:
import json
import numpy as np
import pandas as pd

reference_maps = ['ETH', 'GLAD', 'META', 'PAULS']

with open('/n/tambe_lab/Everyone/tree_mapping/results.json') as f:
    results = json.load(f)

In [4]:
metrics = ['mae', 'r2', 'rmse', 'mse']

In [5]:
results_print_ref = pd.DataFrame()

for ref_map in reference_maps:
    row = pd.DataFrame(results[ref_map]['total'], index=[ref_map])
    results_print_ref = pd.concat((results_print_ref,row))

In [6]:
results_print_ref[['mae', 'r2', 'rmse']].round(2)

        mae    r2  rmse
ETH    3.83 -2.26  4.51
GLAD   2.44 -0.53  3.09
META   2.87 -0.98  3.51
PAULS  2.01  0.05  2.43

In [7]:
models = list(results.keys())
for ref_map in reference_maps: models.remove(ref_map)

In [8]:
results_print_models_by_seed = pd.DataFrame()
num_trials = 10
for model in models:
    for trial in np.arange(num_trials):
        row = results[model]['12 train sites'][f'seed {trial}']['total']
        row.update({'model': model, 'trial_seed': trial})
        results_print_models_by_seed = pd.concat([results_print_models_by_seed, pd.DataFrame([row])])

In [9]:
df_mean = results_print_models_by_seed.groupby('model').mean()
df_stddev = results_print_models_by_seed.groupby('model').std()
df_stddev = df_stddev.rename(columns= {x: f'{x} (stddev)' for x in df_stddev.columns})
df_print = df_mean.join(df_stddev)


columns_print = ['rmse', f'rmse (stddev)', 'mae', f'mae (stddev)', 'r2', f'r2 (stddev)']
models_print = ['finetune_xceptionS2/pretrained/3_layers_tuned',
                'finetune_xceptionS2/randominit_nolatlon/3_layers_tuned',
                'finetune_xceptionS2/randominit_latlon/3_layers_tuned',
                'unet/pretrained/freeze_backbone_True',
                'unet/pretrained/freeze_backbone_False',
                'unet/randominit/12_channels',
                'local_only_models/128_filters/12_channels',
                'random_forest/12_channels']

df_print.loc[models_print,columns_print].round(2)

,rmse,rmse (stddev),mae,mae (stddev),r2,r2 (stddev)
model,,,,,,
finetune_xceptionS2/pretrained/3_layers_tuned,1.98,0.03,1.48,0.02,0.37,0.02
finetune_xceptionS2/randominit_nolatlon/3_layers_tuned,1.94,0.03,1.47,0.02,0.40,0.02
finetune_xceptionS2/randominit_latlon/3_layers_tuned,2.05,0.04,1.55,0.03,0.33,0.03
unet/pretrained/freeze_backbone_True,2.05,0.04,1.54,0.03,0.32,0.03
unet/pretrained/freeze_backbone_False,2.08,0.13,1.55,0.10,0.30,0.09
unet/randominit/12_channels,2.27,0.69,1.59,0.20,0.10,0.69
local_only_models/128_filters/12_channels,1.64,0.01,1.20,0.01,0.57,0.00
random_forest/12_channels,2.28,0.00,1.80,0.00,0.16,0.00

In [8]:
# appendix table for different number of xception layers tuned

base_models = ['finetune_xceptionS2/pretrained',
               'finetune_xceptionS2/randominit_nolatlon',
               'finetune_xceptionS2/randominit_latlon'
              ]
models_print_app = [[f'{base_model}/{i}_layers_tuned' for i in range(1,4)] for base_model in base_models]
models_print_app = list(np.ravel(models_print_app))

In [9]:
df_print.loc[models_print_app,columns_print].round(2)

,rmse,rmse (stddev),mae,mae (stddev),r2,r2 (stddev)
model,,,,,,
finetune_xceptionS2/pretrained/1_layers_tuned,2.09,0.02,1.58,0.02,0.30,0.01
finetune_xceptionS2/pretrained/2_layers_tuned,1.97,0.03,1.47,0.02,0.38,0.02
finetune_xceptionS2/pretrained/3_layers_tuned,1.98,0.03,1.48,0.02,0.37,0.02
finetune_xceptionS2/randominit_nolatlon/1_layers_tuned,2.21,0.02,1.72,0.02,0.22,0.02
finetune_xceptionS2/randominit_nolatlon/2_layers_tuned,1.97,0.03,1.49,0.03,0.38,0.02
finetune_xceptionS2/randominit_nolatlon/3_layers_tuned,1.94,0.03,1.47,0.02,0.40,0.02
finetune_xceptionS2/randominit_latlon/1_layers_tuned,2.31,0.05,1.82,0.04,0.15,0.03
finetune_xceptionS2/randominit_latlon/2_layers_tuned,2.08,0.05,1.58,0.04,0.31,0.03
finetune_xceptionS2/randominit_latlon/3_layers_tuned,2.05,0.04,1.55,0.03,0.33,0.03

In [10]:
df_print.loc[models_print_app,columns_print].round(2).to_latex(float_format="%.2f")

'\\begin{tabular}{lrrrrrr}\n\\toprule\n & rmse & rmse (stddev) & mae & mae (stddev) & r2 & r2 (stddev) \\\\\nmodel &  &  &  &  &  &  \\\\\n\\midrule\nfinetune_xceptionS2/pretrained/1_layers_tuned & 2.09 & 0.02 & 1.58 & 0.02 & 0.30 & 0.01 \\\\\nfinetune_xceptionS2/pretrained/2_layers_tuned & 1.97 & 0.03 & 1.47 & 0.02 & 0.38 & 0.02 \\\\\nfinetune_xceptionS2/pretrained/3_layers_tuned & 1.98 & 0.03 & 1.48 & 0.02 & 0.37 & 0.02 \\\\\nfinetune_xceptionS2/randominit_nolatlon/1_layers_tuned & 2.21 & 0.02 & 1.72 & 0.02 & 0.22 & 0.02 \\\\\nfinetune_xceptionS2/randominit_nolatlon/2_layers_tuned & 1.97 & 0.03 & 1.49 & 0.03 & 0.38 & 0.02 \\\\\nfinetune_xceptionS2/randominit_nolatlon/3_layers_tuned & 1.94 & 0.03 & 1.47 & 0.02 & 0.40 & 0.02 \\\\\nfinetune_xceptionS2/randominit_latlon/1_layers_tuned & 2.31 & 0.05 & 1.82 & 0.04 & 0.15 & 0.03 \\\\\nfinetune_xceptionS2/randominit_latlon/2_layers_tuned & 2.08 & 0.05 & 1.58 & 0.04 & 0.31 & 0.03 \\\\\nfinetune_xceptionS2/randominit_latlon/3_layers_tuned & 2.05 & 0.04 & 1.55 & 0.03 & 0.33 & 0.03 \\\\\n\\bottomrule\n\\end{tabular}\n'